from __future__ import annotations

import re
from pathlib import Path

from docx import Document

ROOT = Path(__file__).resolve().parents[1]
SOURCE_DOCX = Path(r"C:\Users\LiamWalsh\Downloads\Notthingham_tumeric_study_report_v4 (6).docx")
OUTPUT_DOCX = ROOT / "Notthingham_tumeric_study_report_v4_6_improved_references_fixed.docx"
REPORT_OUTPUT_DOCX = ROOT / "results" / "Processed" / "06_reports" / "Notthingham_tumeric_study_report_v4_6_improved_references_fixed.docx"
REPO_URL = "https://github.com/LiamHWalsh/NTU_Teagasc_Turmeric_study"


def clear_paragraph(paragraph) -> None:
    element = paragraph._element
    for child in list(element):
        element.remove(child)


def set_paragraph(paragraph, text: str) -> None:
    style = paragraph.style
    clear_paragraph(paragraph)
    paragraph.style = style
    parts = re.split(r"(<i>.*?</i>)", text)
    for part in parts:
        if not part:
            continue
        if part.startswith("<i>") and part.endswith("</i>"):
            run = paragraph.add_run(part[3:-4])
            run.italic = True
        else:
            paragraph.add_run(part)


def main() -> None:
    doc = Document(str(SOURCE_DOCX))

    replacements = {
        12: "turmeric, curcumin, gut microbiome, elite athletes, soccer, shotgun metagenomics, alpha diversity, functional pathways",
        14: "Turmeric is widely used as a dietary bioactive, but its longitudinal effects on the gut microbiome in elite athletes remain incompletely defined. We investigated this in a pilot cohort of professional soccer players followed across a competitive season.",
        15: "Shotgun metagenomic profiling showed that turmeric exposure was associated with modest microbiome modulation rather than large community-wide restructuring. Species-level alpha diversity tended to decrease, whereas functional alpha diversity remained comparatively stable, and global beta-diversity analyses did not show robust treatment-control separation.",
        16: "Exploratory feature-level analyses identified structured but mixed responses, including a positive <i>Blautia</i> signal, a negative <i>Alistipes</i> signal, additional strain-level changes such as <i>Bifidobacterium catenulatum</i> and <i>Parabacteroides distasonis</i>, and bidirectional pathway shifts. Taxonomy-function integration yielded several exploratory co-variation signals, including some meeting an exploratory false-discovery threshold, but these findings remained non-confirmatory in this small cohort. Overall, turmeric was associated with subtle, feature-level microbiome changes without clear evidence of broad functional disruption. These results are hypothesis-generating and support targeted replication in larger, adequately powered longitudinal studies.",
        20: "There is growing recognition that the human gut microbiota, which contains bacteria, archaea, viruses, and eukaryotic microbes, contributes to digestion, metabolic regulation, immune signaling, and inflammatory control. These functions are directly relevant to athlete health and performance. Previous work suggests that elite athletes can harbor distinct gut microbial compositions and metabolic functions relative to non-athlete cohorts [1]. Despite the widespread use of dietary supplements in elite sport, the extent to which such interventions shape the athlete gut microbiome remains uncertain.",
        22: "Turmeric (<i>Curcuma longa</i>) contains multiple bioactive compounds, including curcuminoids, turmerones, and polysaccharides. Human evidence for microbiome effects remains limited and inconsistent. In a double-blind randomized pilot trial, supplementation with turmeric plus piperine or curcumin plus piperine for 8 weeks produced individualized changes in gut microbial composition without clear group-level significance [2]. A larger randomized trial in adults with digestive complaints similarly reported symptomatic improvement with turmeric extract but only modest microbiome shifts [3]. Together, these findings suggest that turmeric-related microbiome effects may be subtle, context dependent, and not necessarily expressed as large changes in community-wide diversity.",
        24: "Mechanistic and preclinical work nevertheless supports biological plausibility. Gut microbes can metabolize curcumin via reduction and demethylation pathways, generating downstream metabolites that may retain biological activity [4]. Experimental studies have reported curcumin-associated changes in <i>Bifidobacterium</i>, <i>Lactobacillus</i>, <i>Akkermansia</i>, and other taxa, together with altered short-chain fatty acid production and inflammatory signaling [5-7]. Curcumin has also been shown to modulate intestinal barrier function through effects on tight-junction regulation and epithelial inflammatory pathways [8]. However, differences in dose, formulation, exposure duration, and bioavailability limit direct translation from preclinical systems to free-living human populations.",
        26: "Soccer players represent a useful cohort for studying longitudinal microbiome variability because their season contains repeated cycles of high training load, competition, travel, and recovery. Competitive play can challenge gastrointestinal physiology through exercise-associated splanchnic hypoperfusion and gut dysfunction [9], while match play and intensive training are accompanied by substantial increases in markers of muscle damage and inflammatory stress [10]. Elite clubs may also accumulate heavy fixture schedules across domestic and cup competitions, and congested phases commonly involve recovery windows of 48-72 hours between matches [11,12]. This combination of repeated physiological strain and constrained recovery creates a setting in which nutritional strategies could plausibly influence intestinal microbial ecology.",
        27: "A recent study using the same turmeric-containing formulation reported attenuation of post-match gut-permeability and inflammatory responses in elite soccer players [13]. Against that background, the aim of the present pilot study was to evaluate whether daily raw turmeric supplementation was associated with longitudinal shifts in gut microbiome composition and functional potential across a professional soccer season, using both community-level diversity analyses and exploratory feature-level effect-size prioritization.",
        36: f"Paired-end metagenomic sequencing reads were processed using a reproducible Nextflow-based pipeline integrating Fasnicar, MetaPhlAn, and HUMAnN3 (code available at {REPO_URL}).",
        43: f"All statistical analyses were performed in R (v4.4.x; R Foundation for Statistical Computing, Vienna, Austria) using RStudio. Analysis scripts, derived tables, and figure outputs were programmatically archived in a version-controlled GitHub repository ({REPO_URL}) to support reproducibility.",
        45: "Alpha diversity was quantified at species and functional levels using Hill numbers implemented in hillR (v0.5.2) [15]: richness (q = 0), Shannon diversity (q = 1), and Simpson diversity (q = 2), calculated from relative-abundance profiles. Each alpha-diversity endpoint was analyzed separately using Bayesian linear mixed-effects models implemented in brms (v2.23.0) [16] with Gaussian likelihood and identity link. Fixed effects were turmeric status and timepoint; participant ID was modeled as a random intercept to account for repeated measurements. Priors were prespecified for regularization: Normal(0, 5) for fixed-effect coefficients, half-Student-t(3, 0, 5) for random-intercept SDs, and half-Student-t(3, 0, 10) for residual SD. Posterior sampling used NUTS (4 chains; 4,000 iterations/chain; 2,000 warmup; 8,000 post-warmup draws total; adapt_delta = 0.95; max_treedepth = 15). Model adequacy was assessed using Rhat, effective sample size, and posterior predictive checks. Estimates are reported as posterior means with 95% credible intervals and directional posterior probabilities.",
        48: "Given the small and imbalanced groups, the primary global test was an exact permutation test on participant-level CLR change vectors (month 6 minus baseline). Between-group separation was summarized by pseudo-F, and significance was evaluated by exhaustive label permutation preserving group sizes (choose(11,8) = 165 allocations).",
        49: "PERMANOVA (vegan) was used as secondary sensitivity analysis: (i) a 6-month-only turmeric-vs-control comparison and (ii) a full longitudinal turmeric-status x timepoint model (reported diagnostically where interaction terms were non-estimable). Homogeneity of multivariate dispersion was evaluated with PERMDISP for turmeric status and timepoint. PCoA and NMDS were used for visualization only.",
        52: "To complement model-based analyses, we performed an exploratory change-score analysis. For each feature, participant-level delta was defined as month 6 minus baseline abundance; the estimand was the between-group difference in mean delta (turmeric minus control). Participants coded as “Stopped” (3-month turmeric only) were excluded; controls were retained. Metadata retention yielded 16 participants and 40 samples across baseline, 2 weeks, and 6 months; effect estimation used the paired baseline/6-month subset (n = 11; 8 vs 3). Feature filtering was applied before effect estimation. Taxonomic features were retained if prevalence was at least 20% and mean abundance was at least 0.001, whereas pathway features were retained if prevalence was at least 20% and mean abundance was at least 1.0 CPM. With 40 retained samples, the prevalence threshold corresponded to presence in at least 8 samples.",
        53: "For strain-resolution analyses, taxonomy was restricted to strain-resolved entries (t__). The genus panel was defined a priori from the human pilot turmeric/curcumin literature context (<i>Bacteroides</i>, <i>Bifidobacterium</i>, <i>Alistipes</i>, <i>Parabacteroides</i>, <i>Blautia</i>), restricted to genera retained after filtering. Strain-level inference was run on all retained strains within these genera; pathway inference was run on all retained pathways after filtering. Final analyzed panels comprised 29 strain entries, 5 genera, and 339 pathways.",
        54: "Uncertainty for the primary estimand was quantified using 95% bootstrap confidence intervals (2,000 resamples). Cohen’s d and probability of superiority were reported as descriptive ranking metrics only and were not used as confirmatory feature-level tests in this low-N setting. Bootstrap intervals correspond to mean-delta differences, not standardized effects.",
        55: "Raw abundance was used as the primary scale; log1p-transformed values were used for directional sensitivity. Taxonomy panels were additionally assessed using CLR sensitivity, with CLR-derived standardized effects (d_CLR) reported for prioritized features.",
        56: "Participant-level sensitivity was assessed using leave-one-participant-out (LOO) re-estimation. LOO sign agreement was defined as the proportion of valid folds matching the full-sample direction (13 valid folds under minimum group-size constraints). Features were prioritized by a consensus ranking combining |d|, CI width, and LOO sign agreement.",
        57: "Taxonomy-function integration paired the available top-ranked genera (n = 5) with the top 20 pathways (100 pairs). Spearman rho was calculated on participant-level deltas, with 95% bootstrap confidence intervals (2,000 resamples), permutation p-values (2,000 permutations), and BH-adjusted q-values. Exploratory multiplicity interpretation used q < 0.10 as the primary exploratory threshold.",
        59: "As a post hoc exploratory layer, we tested whether microbiome change scores were associated with external-load and health-burden metadata from GPS and injury data_23_10.xlsx. To remain aligned with the primary microbiome comparison framework, analyses were restricted to the same paired treatment/control subset (n = 11; Treatment n = 8, Control n = 3). The source workbook defined two exposure windows: a pre-turmeric period spanning the 14-week pre-season up to Visit 2, and a post-turmeric period spanning the 24-week season up to Visit 3. From these windows we extracted training totals, training minutes per week, match totals, match minutes per week, injury/illness days and percentages, and derived window-to-window deltas. Workbook header structure was validated programmatically before parsing to prevent silent column misalignment.",
        61: "Microbiome outcomes were participant-level deltas defined as month 6 minus mean(Baseline, 2_weeks). Outcomes included alpha-diversity metrics (Richness, Shannon, Simpson) and all retained feature-level signals carried forward from the strain-focused exploratory pipeline (29 strains, 5 genera, 339 pathways). Associations were first tested using Spearman correlation (unadjusted) and partial Spearman correlation adjusted for turmeric_group via rank residualization (rank-transform outcome and predictor, regress each on turmeric_group, then correlate residuals).",
        63: "To align this section with the broader Bayesian framework used elsewhere in the manuscript, we added a Bayesian sensitivity layer using rank-based linear models with conjugate normal-inverse-gamma priors. Outcome and predictor ranks were z-standardized before fitting. For each association, we report posterior mean rank-scale slope (beta_rank), 95% credible interval, posterior direction probability (P(beta > 0) or P(beta < 0), whichever is larger), and two-sided posterior tail probability (p_tail = 2 x min[P(beta > 0), P(beta < 0)]). Tests required at least 8 complete participant pairs.",
        64: "Multiplicity was controlled with Benjamini-Hochberg correction within each panel and model layer (alpha panel: 54 tests; feature-signal panel: 6,714 tests). For Bayesian outputs, BH correction was applied to posterior tail probabilities (q_tail_bh). We reported two exploratory evidence tiers: a primary tier (q < 0.10 or q_tail_bh < 0.10) and a secondary permissive tier (0.10 <= q < 0.20 or 0.10 <= q_tail_bh < 0.20) used only for hypothesis prioritization.",
        66: "Alpha-diversity outcomes were visualized using boxplots overlaid with individual observations and within-participant trajectories. Beta-diversity ordinations were visualized using principal coordinates analysis (PCoA) and non-metric multidimensional scaling (NMDS) on Bray-Curtis dissimilarity matrices; ordination plots were descriptive and not used for inference.",
        68: "Feature-level outputs and summary figures were generated with ggplot2 (v4.0.1) [17].",
        82: "PCoA ordination of Bray-Curtis dissimilarity for (A) species-level and (B) functional-level community composition. Points represent individual samples colored by 6-month turmeric-exposure status and shaped by timepoint. Dashed ellipses indicate 95% confidence regions for each turmeric-status x timepoint combination. These ordinations are descriptive only; inferential beta-diversity results are reported in the main text and were negative for the primary exact CLR-delta test in both data layers.",
        83: "Exploratory Change-Score Analysis Identifies Bidirectional Strain and Pathway Signals",
        84: "The paired exploratory subset included 11 participants (turmeric n = 8; control n = 3). Across the retained panels, confidence intervals for mean delta differences excluded zero for 13/29 strain features (44.8%), 2/5 genera (40.0%), and 109/339 pathways (32.2%). Median absolute standardized effects were 0.71 for strains, 0.83 for genera, and 0.67 for pathways; median CI width was 0.88 for strains, 4.93 for genera, and 104.58 CPM for pathways (Figure 3A-B).",
        85: "Raw-versus-log1p directional agreement was 1.00 for strains, 1.00 for genera, and 0.94 for pathways. Median leave-one-participant-out sign agreement was 1.00 across all panels (Figure 3B-C). At strain level, the strongest positive contrasts clustered within <i>Blautia</i>, led by <i>Blautia wexlerae</i> (SGB4837; d = +2.45; mean delta difference +5.22; 95% CI 3.36 to 7.41), <i>Blautia obeum</i> (SGB4811; d = +1.27; +1.42; 95% CI 0.28 to 2.90), and <i>Blautia</i> sp. MSK_20_85 (SGB4828; d = +1.12; +0.44; 95% CI 0.07 to 0.87). The strongest negative contrasts were <i>Bifidobacterium catenulatum</i> (SGB17241; d = -2.24; -3.07; 95% CI -4.74 to -0.95), <i>Alistipes putredinis</i> (SGB2318; d = -1.46; -3.04; 95% CI -5.01 to -1.08), <i>Alistipes onderdonkii</i> (SGB2303; d = -1.42; -1.30; 95% CI -2.52 to -0.27), and <i>Parabacteroides distasonis</i> (SGB1934; d = -1.40; -0.33; 95% CI -0.59 to -0.08) (Figure 3C). For SGB17241/<i>B. catenulatum</i>, group-specific deltas were treatment mean 0.00 (SD 0.00) and control mean +3.07 (SD 1.94).",
        86: "At genus level, <i>Blautia</i> showed a positive contrast (d = +1.92; +9.65; 95% CI 5.34 to 14.60), whereas <i>Alistipes</i> showed a negative contrast (d = -1.76; -5.19; 95% CI -8.06 to -2.57). Effect estimates for <i>Bacteroides</i>, <i>Bifidobacterium</i>, and <i>Parabacteroides</i> were directionally negative but remained imprecise, with confidence intervals spanning zero.",
        87: "At pathway level, effects were bidirectional rather than uniformly positive (|d| >= 0.8: 64 positive, 80 negative). The strongest positive examples were the superpathway of glycerol degradation to 1,3-propanediol (d = +2.35; +59.49 CPM; 95% CI 36.42 to 85.98) and the superpathway of pyrimidine ribonucleosides degradation (d = +2.13; +38.68 CPM; 95% CI 20.90 to 58.56). Strong negative examples included phytol degradation (d = -1.34), TCA cycle VI (Helicobacter) (d = -1.08), and TCA cycle VII (acetate-producers) (d = -1.11) (Figure 3B-C).",
        88: "Taxonomy-function integration tested 100 genus-pathway pairs. Five pairs had |rho| >= 0.80 and 25 pairs had permutation p < 0.05; 13 pairs met the exploratory BH threshold of q < 0.10 (minimum q = 0.025). The strongest examples were <i>Blautia</i> with the superpathway of glycerol degradation to 1,3-propanediol (rho = +0.918) and <i>Alistipes</i> with 2-oxobutanoate degradation I (rho = +0.891) (Figure 3D). Supplementary Figures S1-S4 present the complete panels: S1 (all analyzed strain-resolved features), S2 (all analyzed genera), S3 (all analyzed pathways), and S4 (all tested genus-pathway pairs).",
        95: "Four-panel summary of paired participant-level deltas (6 months minus baseline; n = 11, turmeric n = 8, control n = 3). (A) Proportion of features with 95% bootstrap confidence intervals excluding zero at strain, genus, and pathway levels. (B) Distribution of absolute effect sizes (|Cohen’s d|) across all tested features; points are colored by CI status (red = CI excludes zero, blue = CI includes zero). (C) Top-ranked strain, genus, and pathway features based on a consensus rank combining effect magnitude, CI width, and leave-one-participant-out (LOO) sign agreement; point size reflects LOO sign agreement and open symbols denote confidence intervals that include zero. (D) Top taxonomy-function candidate pairs from participant-level delta correlations. Thirteen genus-pathway pairs met the exploratory BH threshold of q < 0.10 (minimum q = 0.025); all findings remain hypothesis-generating.",
        96: "Exploratory GPS/Injury Associations Converge on a Pathway-Load Signal",
        97: "Across the GPS/injury analysis, evidence concentrated in feature-level associations rather than alpha diversity. In the alpha-diversity panel (54 tests), five associations were nominally significant in both unadjusted and turmeric-adjusted frequentist models (p < 0.05), but none survived multiplicity correction (unadjusted all q >= 0.29; adjusted all q >= 0.42) and none entered the secondary tier (0.10 <= q < 0.20). The strongest alpha signal remained positive, linking higher total injury days with higher Richness delta (unadjusted rho = 0.761, p = 0.0065, q = 0.291; adjusted rho = 0.751, p = 0.0078, q = 0.420).",
        98: "In the feature-signal panel (6,714 tests spanning 29 strains, 5 genera, and 339 pathways), unadjusted analysis yielded 495 nominal associations (p < 0.05) and two BH-significant associations, both involving the same pathway signal: higher pre-turmeric training load (pre_training_total and pre_training_min_week) was associated with lower delta in pathway PWY-7328 (superpathway of UDP-glucose-derived O-antigen building blocks biosynthesis; both rho = -0.982, both q = 0.00028). After adjustment for turmeric_group, 576 nominal associations were observed and the same two pathway-load associations remained BH-significant (both rho = -0.982, both q = 0.00030). Bayesian rank-model results were directionally concordant: no alpha-diversity association reached the primary Bayesian threshold, whereas the same PWY-7328 signal met the primary tier in both unadjusted and adjusted models for pre_training_total and pre_training_min_week (adjusted beta_rank = -0.981, 95% CrI -1.22 to -0.75, q_tail_bh = 0.0033). Because pre_training_total and pre_training_min_week are alternative summaries of the same pre-Visit-2 window, they should be treated as one convergent pathway-load signal rather than as two independent discoveries.",
        100: "Across analytic scales, turmeric exposure was associated with modest microbiome modulation rather than a strong global community shift. Species-level alpha diversity tended to decrease, particularly for Shannon and Simpson metrics, whereas functional alpha diversity remained comparatively stable (Figure 1). In parallel, exact CLR-delta testing and secondary PERMANOVA did not detect robust treatment-control separation in global beta diversity (Figure 2). The combined interpretation is that turmeric-related effects were concentrated in selected features rather than expressed as large whole-community displacement.",
        101: "Feature-level analyses support this interpretation. Under the literature-anchored genus panel (<i>Bacteroides</i>, <i>Bifidobacterium</i>, <i>Alistipes</i>, <i>Parabacteroides</i>, <i>Blautia</i>), exploratory change-score analysis identified a positive <i>Blautia</i> signal and a negative <i>Alistipes</i> signal at genus level, with additional strain-level decreases involving <i>Bifidobacterium catenulatum</i>, <i>Alistipes</i> spp., and <i>Parabacteroides distasonis</i> (Figure 3C). Under uncapped all-pathway inference, functional effects were likewise bidirectional (64 positive and 80 negative pathways at |d| >= 0.8), arguing against a uniform pathway response to turmeric. Pathway uncertainty remained substantial, and near-identical pathway estimates still indicate annotation redundancy rather than fully independent replication signals.",
        102: "The <i>Eubacterium rectale</i> finding remains biologically relevant but statistically provisional. In the exploratory pipeline, <i>E. rectale</i> showed a positive change-score contrast; in MaAsLin3 triangulation, coefficients were also positive, but abundance-model results were not FDR-significant and prevalence-model outputs carried a small-random-effects warning. Accordingly, this taxon should be treated as a replication candidate rather than a validated endpoint.",
        103: "Results are only partially concordant with prior preclinical curcumin literature reporting enrichment of <i>Bifidobacterium</i>, <i>Lactobacillus</i>, and other putatively beneficial taxa [5-8]. In this cohort, the strongest negative strain-level contrast (SGB17241) was driven by a control-group increase (treatment mean delta 0.00; control mean delta +3.07), limiting causal interpretation. This divergence may reflect cohort context, baseline composition, dose or formulation differences, or low-N sampling variability.",
        104: "From an applied perspective, preservation of functional diversity and absence of robust global functional separation suggest that 6-month turmeric intake did not disrupt core functional capacity of the gut microbiome in this cohort. This profile differs from the broad taxonomic and functional perturbation commonly observed after antibiotic exposure [20], and is compatible with microbiome resilience under competitive-season stress in elite soccer athletes [21].",
        105: "Exploratory GPS/injury association analyses provided limited but internally consistent cross-domain support once all retained microbiome signals were carried forward from the exploratory pipeline. Frequentist and Bayesian sensitivity layers converged on the same primary pathway-level association, linking lower delta in PWY-7328 (superpathway of UDP-glucose-derived O-antigen building blocks biosynthesis) with higher pre-turmeric training load over the 14-week pre-season window. Additional secondary-tier signals, including strain SGB2328 with match-load delta, did not remain at the primary threshold after multiplicity correction across the expanded feature set. Because the surviving association is dominated by one pathway and by highly collinear representations of the same exposure window, it should be interpreted as an exploratory prioritization signal rather than as independent confirmatory evidence.",
        106: "Several limitations materially constrain inference. The paired subset was small and imbalanced (n = 11; 8 vs 3), reducing precision and increasing sensitivity to single-participant effects. Baseline imbalance was not explicitly adjusted in the change-score contrasts. Strain-level identifiers were SGB-based and not always directly interpretable as named species, pathway redundancy was present, and taxonomy-function associations meeting q < 0.10 remain vulnerable to multiplicity and overfitting in this sample size. Directional robustness diagnostics (LOO and transform agreement) should therefore be interpreted as internal sensitivity checks, not external validation.",
        107: "Overall, the most defensible output is a prioritized feature set for replication. Future work should use larger balanced cohorts, pre-specified primary endpoints, explicit baseline adjustment, and denser longitudinal sampling across training-load peaks, congested fixture periods, travel phases, and off-season windows.",
        108: "",
        109: "",
        110: "",
        112: "Turmeric consumption in this pilot elite-athlete cohort was associated with modest, directionally structured microbiome changes, with stronger signals at feature level than at global diversity level. These findings are hypothesis-generating and support targeted replication of prioritized taxa and pathways in adequately powered longitudinal studies.",
        119: f"Computer code used in data analysis is available at {REPO_URL}",
        131: "Supplementary Figure S1. All analyzed strain-level change-score effects (n = 29 features).\nForest plot including all retained strain-resolved taxonomic features (SGB identifiers). Points show Cohen’s d for the between-group contrast in baseline-to-6-month change (turmeric minus control), and horizontal bars show 95% bootstrap intervals from the delta-contrast workflow (2,000 resamples). Features are ordered by consensus rank combining effect magnitude, interval width, and leave-one-participant-out (LOO) directional agreement.",
        133: "Supplementary Figure S2. All analyzed genus-level change-score effects (n = 5 features).\nForest plot of all retained genera using the same analytic framework as Figure 3. Points represent Cohen’s d for between-group delta contrasts, with 95% bootstrap intervals (2,000 resamples). Feature ordering and color coding follow the primary ranking scheme.",
        135: "Supplementary Figure S3. All analyzed pathway-level change-score effects (n = 339 features).\nForest plot of all retained pathways from the exploratory change-score analysis. Points represent Cohen’s d and horizontal bars represent 95% bootstrap intervals (2,000 resamples). Pathway effects are shown for the full filtered panel rather than a capped subset.",
        138: "Supplementary Figure S4. Full taxonomy-function integration map (n = 100 genus-pathway pairs).\nSpearman correlation coefficients (rho) for all tested genus-pathway delta pairs, with 95% bootstrap intervals (2,000 resamples). Red points indicate nominal permutation significance (p < 0.05); gray points indicate p >= 0.05. Vertical dotted lines at rho = ±0.8 indicate high-magnitude correlation thresholds. Thirteen pairs met the exploratory BH threshold of q < 0.10.",
    }

    for idx, text in replacements.items():
        set_paragraph(doc.paragraphs[idx], text)
    references = [
        "1. Clarke SF, Murphy EF, O’Sullivan O, et al. Exercise and associated dietary extremes impact on gut microbial diversity. Gut. 2014;63(12):1913-1920. doi:10.1136/gutjnl-2013-306541.",
        "2. Peterson CT, Vaughn AR, Sharma V, et al. Effects of turmeric and curcumin dietary supplementation on human gut microbiota: a double-blind, randomized, placebo-controlled pilot study. J Evid Based Integr Med. 2018;23:2515690X18790725. doi:10.1177/2515690X18790725.",
        "3. Lopresti AL, Smith SJ, Metse AP, Drummond PD. Efficacy of a curcumin extract (Curcugen) on gastrointestinal symptoms and intestinal microbiota in adults with self-reported digestive complaints: a randomized, double-blind, placebo-controlled study. BMC Complement Med Ther. 2021;21:40. doi:10.1186/s12906-021-03202-5.",
        "4. Scazzocchio B, Minghetti L, D’Archivio M. Interaction between gut microbiota and curcumin: a new key of understanding for the health effects of curcumin. Nutrients. 2020;12(9):2499. doi:10.3390/nu12092499.",
        "5. Shen L, Liu L, Ji HF. Regulative effects of curcumin spice administration on gut microbiota and its pharmacological implications. Food Nutr Res. 2017;61(1):1361780. doi:10.1080/16546628.2017.1361780.",
        "6. Neyrinck AM, Sanchez CRM, Taminiau B, et al. Curcuma longa extract associated with white pepper lessens high fat diet-induced inflammation in subcutaneous adipose tissue in mice. PLoS One. 2021;16(2):e0245220. doi:10.1371/journal.pone.0245220.",
        "7. Deng H, Feng Y, Zhou Z, et al. Curcumin suppresses colorectal tumorigenesis through restoring the gut microbiota and metabolites. J Exp Clin Cancer Res. 2024;43:306. doi:10.1186/s13046-024-03186-6.",
        "8. Wang J, Ghosh SS, Ghosh S. Curcumin improves intestinal barrier function: modulation of intracellular signaling and organization of tight junctions. Am J Physiol Cell Physiol. 2017;312(4):C438-C445. doi:10.1152/ajpcell.00235.2016.",
        "9. van Wijck K, Lenaerts K, van Loon LJC, et al. Exercise-induced splanchnic hypoperfusion results in gut dysfunction in healthy men. PLoS One. 2011;6(7):e22366. doi:10.1371/journal.pone.0022366.",
        "10. Saidi S, de Sousa CV, Olher RR, et al. Physiology and methodology of biomarkers in soccer: a systematic review and meta-analysis. Biol Sport. 2021;39(2):463-470. doi:10.5114/biolsport.2021.103574.",
        "11. Page RM, Gregson W, Jones B. Effects of fixture congestion on injury, physical performance and wellness in football: a systematic review. Sports Med. 2023;53(8):1477-1499. doi:10.1007/s40279-023-01819-1.",
        "12. Wilke J, Behrens M, Granacher U. Match interval and recovery outcomes in football: can 48 hours separation from the previous match be as good as 72 hours? Eur J Sport Sci. 2024;24(6):1072-1081. doi:10.1002/ejsc.12152.",
        "13. Clayton DJ, Fenn D, Stanger M, et al. Curcumin and vitamins C and D attenuate post-match gut permeability and inflammation in elite football players. Eur J Sport Sci. 2024;24(11):2739-2753. doi:10.1002/ejsc.12117.",
        "14. Franzosa EA, McIver LJ, Rahnavard G, et al. Species-level functional profiling of metagenomes and metatranscriptomes. Nat Methods. 2018;15(11):962-968. doi:10.1038/s41592-018-0176-y.",
        "15. Li D. hillR: taxonomic, functional, and phylogenetic diversity and similarity through Hill numbers. J Open Source Softw. 2018;3(31):1041. doi:10.21105/joss.01041.",
        "16. Bürkner PC. brms: an R package for Bayesian multilevel models using Stan. J Stat Softw. 2017;80(1):1-28. doi:10.18637/jss.v080.i01.",
        "17. Wickham H. ggplot2: Elegant Graphics for Data Analysis. New York: Springer-Verlag; 2016.",
        "18. Louca S, Polz MF, Mazel F, et al. Function and functional redundancy in microbial systems. Nat Ecol Evol. 2018;2(6):936-943. doi:10.1038/s41559-018-0519-1.",
        "19. Moya A, Ferrer M. Functional redundancy-induced stability of gut microbiota subjected to disturbance. Trends Microbiol. 2016;24(5):402-413. doi:10.1016/j.tim.2016.02.002.",
        "20. Lange K, Buerger M, Stallmach A, Bruns T. Effects of antibiotics on gut microbiota. Dig Dis. 2016;34(3):260-268. doi:10.1159/000443360.",
        "21. Oliveira LVL, Taddei CR, Maldonado IRSC, et al. Gut microbiota of elite female football players is not altered during an official international tournament. mSphere. 2022;7(6):e00130-22. doi:10.1128/msphere.00130-22.",
    ]

    set_paragraph(doc.paragraphs[128], references[0])
    reference_style = doc.paragraphs[128].style
    supplement_heading = doc.paragraphs[129]
    for ref in references[1:]:
        new_paragraph = supplement_heading.insert_paragraph_before()
        new_paragraph.style = reference_style
        set_paragraph(new_paragraph, ref)

    OUTPUT_DOCX.parent.mkdir(parents=True, exist_ok=True)
    REPORT_OUTPUT_DOCX.parent.mkdir(parents=True, exist_ok=True)
    doc.save(str(OUTPUT_DOCX))
    doc.save(str(REPORT_OUTPUT_DOCX))

    print(OUTPUT_DOCX)
    print(REPORT_OUTPUT_DOCX)


if __name__ == "__main__":
    main()
